server:
  port: 8080

spring:
  application:
    name: 'bookapp'
  graphql:
    graphiql:
      enabled: true
    tools:
      schema-parser-options:
        introspection-enabled: false
  datasource:
    url: jdbc:h2:mem:test_db
    driverClassName: org.h2.Driver
    username: fkh
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

